language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules #Cache node_modules for faster builds
script:
  - bash rm -rf ~/node_modules/babel-jest ~/node_modules/jest
  - yarn test #Runs Tests
  - yarn build #Creats a production build
