#Request root permissions to the TravisCI runtime environment
sudo: required
#Tell TravisCI that we're using docker to run our tests
services:
  - docker
before_install:
  - docker build -t prod .
script:
  - docker run -d --restart=always prod
# Add deploy config below
