version: "3"
services:
  wishlist:
    build: .
    restart: always
    ports:
      - 8080:80
  tests: build:.
  volumes:
    - /app/node_modules
    - .:/app
  command: ["yarn", "test"]
# version: "3"
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     volumes:
#       - /app/node_modules
#       - .:/app
# tests:
#   build:
#     context: .
#     dockerfile: Dockerfile.dev
#   volumes:
#     - /app/node_modules
#     - .:/app
#   command: ["yarn", "test"]
