version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["yarn", "test"]
# version: "3"
# services:
#   prod:
#     build: .
#     restart: always
#     ports:
#       - 8080:80
#     volumes:
#       - .:/app
#       - /app/node_modules
# tests:
#   build:
#     context: .
#     dockerfile: Dockerfile.dev
#   volumes:
#     - /app/node_modules
#     - .:/app
#   command: ["yarn", "test"]
# version: "3"
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     volumes:
#       - /app/node_modules
#       - .:/app

