FROM tiangolo/node-frontend:10

WORKDIR '/app'

COPY package.json .

RUN yarn 


COPY . .

CMD ["yarn", "start"]



# FROM node:alpine

# WORKDIR /app

# COPY package.json /app/

# RUN yarn 

# COPY ./ /app/

# CMD ["yarn", "run", "test", "--", "--coverage"]