export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_COMPLETED = "FETCH_COMPLETED";
export const FETCH_FAILED = "FETCH_FAILED";
export const SEARCH_BOX_CLEARED = "SEARCH_BOX_CLEARED";
export const NO_ITEM_FOUND = "NO_ITEM_FOUND";
